### PR TITLE
Bugfix with Django 4.2

### PR DESCRIPTION
**Pull request by amorilla**
There are unused imports than raise error with Django 4.2
from django.core.files.storage import File, Storage 
ImportError: cannot import name 'File' from 'django.core.files.storage'

### CODE REVIEW

**Comment by amorilla** [comment]
Hello,
Could someone review this pull request?
@vdboor @axnsan12 @tomturner @edoburu

Greetings.

**Comment by tomturner** [comment]
@amorilla I had to fork this to get the project to work with Django 4.1. I have added the change in for 4.2  I am not sure if this project is dead.  I would be happy to run it if @edoburu wanted me to do so as I need this for my work project.  I run a large open source project already (django-tenants)

**Comment by bjoernricks** [comment]
Hi,

would it be possible to create a new release on PyPI with this change? I really don't want to fork the project just for this.

**Comment by amorilla** [comment]
new release 3.1 updated at PyPi.
